[package]
name = "cookie-session"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-session = { version = "0.9.0", features = ["cookie-session"] }
actix-web = "4.8.0"
env_logger = "0.11.3"
log = "0.4.22"
